#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=128
#SBATCH --time=08:00:00
#SBATCH --account=su007-pbro

module purge
module load warwick GCC/10.2.0  OpenMPI/4.0.5 iccifort/2019.5.281  OpenMPI/3.1.4 CASTEP/22.11

srun --cpu-bind=rank castep.mpi castep
